[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "django-daterangefilter"
version = "1.2"
dependencies = [
  "django>2.2",
]
authors = [
  {name = "Andrey Novikov", email = "novikov@gmail.com"},
]
description = "Date range filter for Django admin"
readme = "README.md"
license = "MIT"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: Django",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/andreynovikov/django-daterangefilter"
Repository = "https://github.com/andreynovikov/django-daterangefilter.git"
Issues = "https://github.com/andreynovikov/django-daterangefilter/issues"
